
<div style="clear:both;"></div>
<div id="footer">
<p style="font-size:16px;" align="center">All students receive 15% discount on all our dishes.</p>
<div class="footer-inner"><p class="copyright">Copyright © 2014 All rights reserved.</p><p style="text-align: right">mb.iordache@gmail.com</p></div>


<div id="google_translate_element" style="text-align:right"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

</div>


</div> <!-- .eightcol End -->
</div> <!-- .row -->
</div> <!-- #container -->
</div> <!-- #wrapper -->
</body>
</html>